/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.mundipagg.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for GetBalanceResponse type.
 */
public class GetBalanceResponse {
    private String currency;
    private long availableAmount;
    private GetRecipientResponse recipient;
    private long waitingFundsAmount;
    private long transferredAmount;

    /**
     * Default constructor.
     */
    public GetBalanceResponse() {
    }

    /**
     * Initialization constructor.
     * @param  currency  String value for currency.
     * @param  availableAmount  long value for availableAmount.
     * @param  waitingFundsAmount  long value for waitingFundsAmount.
     * @param  transferredAmount  long value for transferredAmount.
     * @param  recipient  GetRecipientResponse value for recipient.
     */
    public GetBalanceResponse(
            String currency,
            long availableAmount,
            long waitingFundsAmount,
            long transferredAmount,
            GetRecipientResponse recipient) {
        this.currency = currency;
        this.availableAmount = availableAmount;
        this.recipient = recipient;
        this.waitingFundsAmount = waitingFundsAmount;
        this.transferredAmount = transferredAmount;
    }

    /**
     * Getter for Currency.
     * Currency
     * @return Returns the String
     */
    @JsonGetter("currency")
    public String getCurrency() {
        return currency;
    }

    /**
     * Setter for Currency.
     * Currency
     * @param currency Value for String
     */
    @JsonSetter("currency")
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * Getter for AvailableAmount.
     * Amount available for transferring
     * @return Returns the long
     */
    @JsonGetter("available_amount")
    public long getAvailableAmount() {
        return availableAmount;
    }

    /**
     * Setter for AvailableAmount.
     * Amount available for transferring
     * @param availableAmount Value for long
     */
    @JsonSetter("available_amount")
    public void setAvailableAmount(long availableAmount) {
        this.availableAmount = availableAmount;
    }

    /**
     * Getter for Recipient.
     * Recipient
     * @return Returns the GetRecipientResponse
     */
    @JsonGetter("recipient")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public GetRecipientResponse getRecipient() {
        return recipient;
    }

    /**
     * Setter for Recipient.
     * Recipient
     * @param recipient Value for GetRecipientResponse
     */
    @JsonSetter("recipient")
    public void setRecipient(GetRecipientResponse recipient) {
        this.recipient = recipient;
    }

    /**
     * Getter for WaitingFundsAmount.
     * @return Returns the long
     */
    @JsonGetter("waiting_funds_amount")
    public long getWaitingFundsAmount() {
        return waitingFundsAmount;
    }

    /**
     * Setter for WaitingFundsAmount.
     * @param waitingFundsAmount Value for long
     */
    @JsonSetter("waiting_funds_amount")
    public void setWaitingFundsAmount(long waitingFundsAmount) {
        this.waitingFundsAmount = waitingFundsAmount;
    }

    /**
     * Getter for TransferredAmount.
     * @return Returns the long
     */
    @JsonGetter("transferred_amount")
    public long getTransferredAmount() {
        return transferredAmount;
    }

    /**
     * Setter for TransferredAmount.
     * @param transferredAmount Value for long
     */
    @JsonSetter("transferred_amount")
    public void setTransferredAmount(long transferredAmount) {
        this.transferredAmount = transferredAmount;
    }

    /**
     * Converts this GetBalanceResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GetBalanceResponse [" + "currency=" + currency + ", availableAmount="
                + availableAmount + ", waitingFundsAmount=" + waitingFundsAmount
                + ", transferredAmount=" + transferredAmount + ", recipient=" + recipient + "]";
    }

    /**
     * Builds a new {@link GetBalanceResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GetBalanceResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(currency, availableAmount, waitingFundsAmount,
                transferredAmount)
                .recipient(getRecipient());
        return builder;
    }

    /**
     * Class to build instances of {@link GetBalanceResponse}.
     */
    public static class Builder {
        private String currency;
        private long availableAmount;
        private long waitingFundsAmount;
        private long transferredAmount;
        private GetRecipientResponse recipient;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  currency  String value for currency.
         * @param  availableAmount  long value for availableAmount.
         * @param  waitingFundsAmount  long value for waitingFundsAmount.
         * @param  transferredAmount  long value for transferredAmount.
         */
        public Builder(String currency, long availableAmount, long waitingFundsAmount,
                long transferredAmount) {
            this.currency = currency;
            this.availableAmount = availableAmount;
            this.waitingFundsAmount = waitingFundsAmount;
            this.transferredAmount = transferredAmount;
        }

        /**
         * Setter for currency.
         * @param  currency  String value for currency.
         * @return Builder
         */
        public Builder currency(String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * Setter for availableAmount.
         * @param  availableAmount  long value for availableAmount.
         * @return Builder
         */
        public Builder availableAmount(long availableAmount) {
            this.availableAmount = availableAmount;
            return this;
        }

        /**
         * Setter for waitingFundsAmount.
         * @param  waitingFundsAmount  long value for waitingFundsAmount.
         * @return Builder
         */
        public Builder waitingFundsAmount(long waitingFundsAmount) {
            this.waitingFundsAmount = waitingFundsAmount;
            return this;
        }

        /**
         * Setter for transferredAmount.
         * @param  transferredAmount  long value for transferredAmount.
         * @return Builder
         */
        public Builder transferredAmount(long transferredAmount) {
            this.transferredAmount = transferredAmount;
            return this;
        }

        /**
         * Setter for recipient.
         * @param  recipient  GetRecipientResponse value for recipient.
         * @return Builder
         */
        public Builder recipient(GetRecipientResponse recipient) {
            this.recipient = recipient;
            return this;
        }

        /**
         * Builds a new {@link GetBalanceResponse} object using the set fields.
         * @return {@link GetBalanceResponse}
         */
        public GetBalanceResponse build() {
            return new GetBalanceResponse(currency, availableAmount, waitingFundsAmount,
                    transferredAmount, recipient);
        }
    }
}
