/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.mundipagg.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for GetUsagesDetailsResponse type.
 */
public class GetUsagesDetailsResponse {
    private String subscriptionId;
    private int totalAmount;
    private GetPeriodResponse period;
    private ListUsagesDetailsResponse usages;
    private Integer totalDiscount;
    private Integer totalIncrement;

    /**
     * Default constructor.
     */
    public GetUsagesDetailsResponse() {
    }

    /**
     * Initialization constructor.
     * @param  subscriptionId  String value for subscriptionId.
     * @param  totalAmount  int value for totalAmount.
     * @param  usages  ListUsagesDetailsResponse value for usages.
     * @param  period  GetPeriodResponse value for period.
     * @param  totalDiscount  Integer value for totalDiscount.
     * @param  totalIncrement  Integer value for totalIncrement.
     */
    public GetUsagesDetailsResponse(
            String subscriptionId,
            int totalAmount,
            ListUsagesDetailsResponse usages,
            GetPeriodResponse period,
            Integer totalDiscount,
            Integer totalIncrement) {
        this.subscriptionId = subscriptionId;
        this.totalAmount = totalAmount;
        this.period = period;
        this.usages = usages;
        this.totalDiscount = totalDiscount;
        this.totalIncrement = totalIncrement;
    }

    /**
     * Getter for SubscriptionId.
     * Subscription Identifier
     * @return Returns the String
     */
    @JsonGetter("subscription_id")
    public String getSubscriptionId() {
        return subscriptionId;
    }

    /**
     * Setter for SubscriptionId.
     * Subscription Identifier
     * @param subscriptionId Value for String
     */
    @JsonSetter("subscription_id")
    public void setSubscriptionId(String subscriptionId) {
        this.subscriptionId = subscriptionId;
    }

    /**
     * Getter for TotalAmount.
     * Current Invoice Amount
     * @return Returns the int
     */
    @JsonGetter("total_amount")
    public int getTotalAmount() {
        return totalAmount;
    }

    /**
     * Setter for TotalAmount.
     * Current Invoice Amount
     * @param totalAmount Value for int
     */
    @JsonSetter("total_amount")
    public void setTotalAmount(int totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * Getter for Period.
     * Period Details
     * @return Returns the GetPeriodResponse
     */
    @JsonGetter("Period")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public GetPeriodResponse getPeriod() {
        return period;
    }

    /**
     * Setter for Period.
     * Period Details
     * @param period Value for GetPeriodResponse
     */
    @JsonSetter("Period")
    public void setPeriod(GetPeriodResponse period) {
        this.period = period;
    }

    /**
     * Getter for Usages.
     * Usages Details
     * @return Returns the ListUsagesDetailsResponse
     */
    @JsonGetter("Usages")
    public ListUsagesDetailsResponse getUsages() {
        return usages;
    }

    /**
     * Setter for Usages.
     * Usages Details
     * @param usages Value for ListUsagesDetailsResponse
     */
    @JsonSetter("Usages")
    public void setUsages(ListUsagesDetailsResponse usages) {
        this.usages = usages;
    }

    /**
     * Getter for TotalDiscount.
     * Total discounted value
     * @return Returns the Integer
     */
    @JsonGetter("total_discount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getTotalDiscount() {
        return totalDiscount;
    }

    /**
     * Setter for TotalDiscount.
     * Total discounted value
     * @param totalDiscount Value for Integer
     */
    @JsonSetter("total_discount")
    public void setTotalDiscount(Integer totalDiscount) {
        this.totalDiscount = totalDiscount;
    }

    /**
     * Getter for TotalIncrement.
     * Total inremented value
     * @return Returns the Integer
     */
    @JsonGetter("total_increment")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getTotalIncrement() {
        return totalIncrement;
    }

    /**
     * Setter for TotalIncrement.
     * Total inremented value
     * @param totalIncrement Value for Integer
     */
    @JsonSetter("total_increment")
    public void setTotalIncrement(Integer totalIncrement) {
        this.totalIncrement = totalIncrement;
    }

    /**
     * Converts this GetUsagesDetailsResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GetUsagesDetailsResponse [" + "subscriptionId=" + subscriptionId + ", totalAmount="
                + totalAmount + ", usages=" + usages + ", period=" + period + ", totalDiscount="
                + totalDiscount + ", totalIncrement=" + totalIncrement + "]";
    }

    /**
     * Builds a new {@link GetUsagesDetailsResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GetUsagesDetailsResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(subscriptionId, totalAmount, usages)
                .period(getPeriod())
                .totalDiscount(getTotalDiscount())
                .totalIncrement(getTotalIncrement());
        return builder;
    }

    /**
     * Class to build instances of {@link GetUsagesDetailsResponse}.
     */
    public static class Builder {
        private String subscriptionId;
        private int totalAmount;
        private ListUsagesDetailsResponse usages;
        private GetPeriodResponse period;
        private Integer totalDiscount;
        private Integer totalIncrement;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  subscriptionId  String value for subscriptionId.
         * @param  totalAmount  int value for totalAmount.
         * @param  usages  ListUsagesDetailsResponse value for usages.
         */
        public Builder(String subscriptionId, int totalAmount, ListUsagesDetailsResponse usages) {
            this.subscriptionId = subscriptionId;
            this.totalAmount = totalAmount;
            this.usages = usages;
        }

        /**
         * Setter for subscriptionId.
         * @param  subscriptionId  String value for subscriptionId.
         * @return Builder
         */
        public Builder subscriptionId(String subscriptionId) {
            this.subscriptionId = subscriptionId;
            return this;
        }

        /**
         * Setter for totalAmount.
         * @param  totalAmount  int value for totalAmount.
         * @return Builder
         */
        public Builder totalAmount(int totalAmount) {
            this.totalAmount = totalAmount;
            return this;
        }

        /**
         * Setter for usages.
         * @param  usages  ListUsagesDetailsResponse value for usages.
         * @return Builder
         */
        public Builder usages(ListUsagesDetailsResponse usages) {
            this.usages = usages;
            return this;
        }

        /**
         * Setter for period.
         * @param  period  GetPeriodResponse value for period.
         * @return Builder
         */
        public Builder period(GetPeriodResponse period) {
            this.period = period;
            return this;
        }

        /**
         * Setter for totalDiscount.
         * @param  totalDiscount  Integer value for totalDiscount.
         * @return Builder
         */
        public Builder totalDiscount(Integer totalDiscount) {
            this.totalDiscount = totalDiscount;
            return this;
        }

        /**
         * Setter for totalIncrement.
         * @param  totalIncrement  Integer value for totalIncrement.
         * @return Builder
         */
        public Builder totalIncrement(Integer totalIncrement) {
            this.totalIncrement = totalIncrement;
            return this;
        }

        /**
         * Builds a new {@link GetUsagesDetailsResponse} object using the set fields.
         * @return {@link GetUsagesDetailsResponse}
         */
        public GetUsagesDetailsResponse build() {
            return new GetUsagesDetailsResponse(subscriptionId, totalAmount, usages, period,
                    totalDiscount, totalIncrement);
        }
    }
}
