<?php

declare(strict_types=1);

/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MundiAPILib\Models;

use stdClass;

/**
 * Options for card installment
 */
class CreateCheckoutCardInstallmentOptionRequest implements \JsonSerializable
{
    /**
     * @var int
     */
    private $number;

    /**
     * @var int
     */
    private $total;

    /**
     * @param int $number
     * @param int $total
     */
    public function __construct(int $number, int $total)
    {
        $this->number = $number;
        $this->total = $total;
    }

    /**
     * Returns Number.
     * Installment quantity
     */
    public function getNumber(): int
    {
        return $this->number;
    }

    /**
     * Sets Number.
     * Installment quantity
     *
     * @required
     * @maps number
     */
    public function setNumber(int $number): void
    {
        $this->number = $number;
    }

    /**
     * Returns Total.
     * Total amount
     */
    public function getTotal(): int
    {
        return $this->total;
    }

    /**
     * Sets Total.
     * Total amount
     *
     * @required
     * @maps total
     */
    public function setTotal(int $total): void
    {
        $this->total = $total;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['number'] = $this->number;
        $json['total']  = $this->total;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
