<?php

declare(strict_types=1);

/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MundiAPILib\Models;

use MundiAPILib\Utils\DateTimeHelper;
use stdClass;

/**
 * Contains the settings for creating a boleto payment
 */
class CreateBoletoPaymentRequest implements \JsonSerializable
{
    /**
     * @var int
     */
    private $retries;

    /**
     * @var string
     */
    private $bank;

    /**
     * @var string
     */
    private $instructions;

    /**
     * @var \DateTime|null
     */
    private $dueAt;

    /**
     * @var CreateAddressRequest
     */
    private $billingAddress;

    /**
     * @var string
     */
    private $billingAddressId;

    /**
     * @var string|null
     */
    private $nossoNumero;

    /**
     * @var string
     */
    private $documentNumber;

    /**
     * @var CreateInterestRequest|null
     */
    private $interest;

    /**
     * @var CreateFineRequest|null
     */
    private $fine;

    /**
     * @var int|null
     */
    private $maxDaysToPayPastDue;

    /**
     * @param int $retries
     * @param string $bank
     * @param string $instructions
     * @param CreateAddressRequest $billingAddress
     * @param string $billingAddressId
     * @param string $documentNumber
     */
    public function __construct(
        int $retries,
        string $bank,
        string $instructions,
        CreateAddressRequest $billingAddress,
        string $billingAddressId,
        string $documentNumber
    ) {
        $this->retries = $retries;
        $this->bank = $bank;
        $this->instructions = $instructions;
        $this->billingAddress = $billingAddress;
        $this->billingAddressId = $billingAddressId;
        $this->documentNumber = $documentNumber;
    }

    /**
     * Returns Retries.
     * Number of retries
     */
    public function getRetries(): int
    {
        return $this->retries;
    }

    /**
     * Sets Retries.
     * Number of retries
     *
     * @required
     * @maps retries
     */
    public function setRetries(int $retries): void
    {
        $this->retries = $retries;
    }

    /**
     * Returns Bank.
     * The bank code, containing three characters. The available codes are on the API specification
     */
    public function getBank(): string
    {
        return $this->bank;
    }

    /**
     * Sets Bank.
     * The bank code, containing three characters. The available codes are on the API specification
     *
     * @required
     * @maps bank
     */
    public function setBank(string $bank): void
    {
        $this->bank = $bank;
    }

    /**
     * Returns Instructions.
     * The instructions field that will be printed on the boleto.
     */
    public function getInstructions(): string
    {
        return $this->instructions;
    }

    /**
     * Sets Instructions.
     * The instructions field that will be printed on the boleto.
     *
     * @required
     * @maps instructions
     */
    public function setInstructions(string $instructions): void
    {
        $this->instructions = $instructions;
    }

    /**
     * Returns Due At.
     * Boleto due date
     */
    public function getDueAt(): ?\DateTime
    {
        return $this->dueAt;
    }

    /**
     * Sets Due At.
     * Boleto due date
     *
     * @maps due_at
     * @factory \MundiAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDueAt(?\DateTime $dueAt): void
    {
        $this->dueAt = $dueAt;
    }

    /**
     * Returns Billing Address.
     * Card's billing address
     */
    public function getBillingAddress(): CreateAddressRequest
    {
        return $this->billingAddress;
    }

    /**
     * Sets Billing Address.
     * Card's billing address
     *
     * @required
     * @maps billing_address
     */
    public function setBillingAddress(CreateAddressRequest $billingAddress): void
    {
        $this->billingAddress = $billingAddress;
    }

    /**
     * Returns Billing Address Id.
     * The address id for the billing address
     */
    public function getBillingAddressId(): string
    {
        return $this->billingAddressId;
    }

    /**
     * Sets Billing Address Id.
     * The address id for the billing address
     *
     * @required
     * @maps billing_address_id
     */
    public function setBillingAddressId(string $billingAddressId): void
    {
        $this->billingAddressId = $billingAddressId;
    }

    /**
     * Returns Nosso Numero.
     * Customer identification number with the bank
     */
    public function getNossoNumero(): ?string
    {
        return $this->nossoNumero;
    }

    /**
     * Sets Nosso Numero.
     * Customer identification number with the bank
     *
     * @maps nosso_numero
     */
    public function setNossoNumero(?string $nossoNumero): void
    {
        $this->nossoNumero = $nossoNumero;
    }

    /**
     * Returns Document Number.
     * Boleto identification
     */
    public function getDocumentNumber(): string
    {
        return $this->documentNumber;
    }

    /**
     * Sets Document Number.
     * Boleto identification
     *
     * @required
     * @maps document_number
     */
    public function setDocumentNumber(string $documentNumber): void
    {
        $this->documentNumber = $documentNumber;
    }

    /**
     * Returns Interest.
     */
    public function getInterest(): ?CreateInterestRequest
    {
        return $this->interest;
    }

    /**
     * Sets Interest.
     *
     * @maps interest
     */
    public function setInterest(?CreateInterestRequest $interest): void
    {
        $this->interest = $interest;
    }

    /**
     * Returns Fine.
     */
    public function getFine(): ?CreateFineRequest
    {
        return $this->fine;
    }

    /**
     * Sets Fine.
     *
     * @maps fine
     */
    public function setFine(?CreateFineRequest $fine): void
    {
        $this->fine = $fine;
    }

    /**
     * Returns Max Days to Pay Past Due.
     */
    public function getMaxDaysToPayPastDue(): ?int
    {
        return $this->maxDaysToPayPastDue;
    }

    /**
     * Sets Max Days to Pay Past Due.
     *
     * @maps max_days_to_pay_past_due
     */
    public function setMaxDaysToPayPastDue(?int $maxDaysToPayPastDue): void
    {
        $this->maxDaysToPayPastDue = $maxDaysToPayPastDue;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['retries']                      = $this->retries;
        $json['bank']                         = $this->bank;
        $json['instructions']                 = $this->instructions;
        if (isset($this->dueAt)) {
            $json['due_at']                   = DateTimeHelper::toRfc3339DateTime($this->dueAt);
        }
        $json['billing_address']              = $this->billingAddress;
        $json['billing_address_id']           = $this->billingAddressId;
        if (isset($this->nossoNumero)) {
            $json['nosso_numero']             = $this->nossoNumero;
        }
        $json['document_number']              = $this->documentNumber;
        if (isset($this->interest)) {
            $json['interest']                 = $this->interest;
        }
        if (isset($this->fine)) {
            $json['fine']                     = $this->fine;
        }
        if (isset($this->maxDaysToPayPastDue)) {
            $json['max_days_to_pay_past_due'] = $this->maxDaysToPayPastDue;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
