<?php

declare(strict_types=1);

/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MundiAPILib\Models;

use stdClass;

/**
 * Checkout card payment request
 */
class CreateCheckoutCreditCardPaymentRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $statementDescriptor;

    /**
     * @var CreateCheckoutCardInstallmentOptionRequest[]|null
     */
    private $installments;

    /**
     * @var CreatePaymentAuthenticationRequest|null
     */
    private $authentication;

    /**
     * @var bool|null
     */
    private $capture;

    /**
     * Returns Statement Descriptor.
     * Card invoice text descriptor
     */
    public function getStatementDescriptor(): ?string
    {
        return $this->statementDescriptor;
    }

    /**
     * Sets Statement Descriptor.
     * Card invoice text descriptor
     *
     * @maps statement_descriptor
     */
    public function setStatementDescriptor(?string $statementDescriptor): void
    {
        $this->statementDescriptor = $statementDescriptor;
    }

    /**
     * Returns Installments.
     * Payment installment options
     *
     * @return CreateCheckoutCardInstallmentOptionRequest[]|null
     */
    public function getInstallments(): ?array
    {
        return $this->installments;
    }

    /**
     * Sets Installments.
     * Payment installment options
     *
     * @maps installments
     *
     * @param CreateCheckoutCardInstallmentOptionRequest[]|null $installments
     */
    public function setInstallments(?array $installments): void
    {
        $this->installments = $installments;
    }

    /**
     * Returns Authentication.
     * Creates payment authentication
     */
    public function getAuthentication(): ?CreatePaymentAuthenticationRequest
    {
        return $this->authentication;
    }

    /**
     * Sets Authentication.
     * Creates payment authentication
     *
     * @maps authentication
     */
    public function setAuthentication(?CreatePaymentAuthenticationRequest $authentication): void
    {
        $this->authentication = $authentication;
    }

    /**
     * Returns Capture.
     * Authorize and capture?
     */
    public function getCapture(): ?bool
    {
        return $this->capture;
    }

    /**
     * Sets Capture.
     * Authorize and capture?
     *
     * @maps capture
     */
    public function setCapture(?bool $capture): void
    {
        $this->capture = $capture;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->statementDescriptor)) {
            $json['statement_descriptor'] = $this->statementDescriptor;
        }
        if (isset($this->installments)) {
            $json['installments']         = $this->installments;
        }
        if (isset($this->authentication)) {
            $json['authentication']       = $this->authentication;
        }
        if (isset($this->capture)) {
            $json['capture']              = $this->capture;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
