<?php

declare(strict_types=1);

/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MundiAPILib\Models;

use stdClass;

/**
 * Request for canceling a subscription
 */
class CreateCancelSubscriptionRequest implements \JsonSerializable
{
    /**
     * @var bool
     */
    private $cancelPendingInvoices;

    /**
     * @param bool $cancelPendingInvoices
     */
    public function __construct(bool $cancelPendingInvoices)
    {
        $this->cancelPendingInvoices = $cancelPendingInvoices;
    }

    /**
     * Returns Cancel Pending Invoices.
     * Indicates if the pending invoices must also be canceled.
     */
    public function getCancelPendingInvoices(): bool
    {
        return $this->cancelPendingInvoices;
    }

    /**
     * Sets Cancel Pending Invoices.
     * Indicates if the pending invoices must also be canceled.
     *
     * @required
     * @maps cancel_pending_invoices
     */
    public function setCancelPendingInvoices(bool $cancelPendingInvoices): void
    {
        $this->cancelPendingInvoices = $cancelPendingInvoices;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['cancel_pending_invoices'] = $this->cancelPendingInvoices;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
