<?php

declare(strict_types=1);

/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MundiAPILib\Models;

use stdClass;

class CreateClearSaleRequest implements \JsonSerializable
{
    /**
     * @var int
     */
    private $customSla;

    /**
     * @param int $customSla
     */
    public function __construct(int $customSla)
    {
        $this->customSla = $customSla;
    }

    /**
     * Returns Custom Sla.
     */
    public function getCustomSla(): int
    {
        return $this->customSla;
    }

    /**
     * Sets Custom Sla.
     *
     * @required
     * @maps custom_sla
     */
    public function setCustomSla(int $customSla): void
    {
        $this->customSla = $customSla;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['custom_sla'] = $this->customSla;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
