<?php

declare(strict_types=1);

/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MundiAPILib\Models;

use stdClass;

/**
 * Options for creating the card
 */
class CreateCardOptionsRequest implements \JsonSerializable
{
    /**
     * @var bool
     */
    private $verifyCard;

    /**
     * @param bool $verifyCard
     */
    public function __construct(bool $verifyCard)
    {
        $this->verifyCard = $verifyCard;
    }

    /**
     * Returns Verify Card.
     * Indicates if the card should be verified before creation. If true, executes an authorization before
     * saving the card.
     */
    public function getVerifyCard(): bool
    {
        return $this->verifyCard;
    }

    /**
     * Sets Verify Card.
     * Indicates if the card should be verified before creation. If true, executes an authorization before
     * saving the card.
     *
     * @required
     * @maps verify_card
     */
    public function setVerifyCard(bool $verifyCard): void
    {
        $this->verifyCard = $verifyCard;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['verify_card'] = $this->verifyCard;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
