<?php

declare(strict_types=1);

/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MundiAPILib\Models;

use stdClass;

/**
 * Checkout bank transfer payment request
 */
class CreateCheckoutBankTransferRequest implements \JsonSerializable
{
    /**
     * @var string[]
     */
    private $bank;

    /**
     * @var int
     */
    private $retries;

    /**
     * @param string[] $bank
     * @param int $retries
     */
    public function __construct(array $bank, int $retries)
    {
        $this->bank = $bank;
        $this->retries = $retries;
    }

    /**
     * Returns Bank.
     * Bank
     *
     * @return string[]
     */
    public function getBank(): array
    {
        return $this->bank;
    }

    /**
     * Sets Bank.
     * Bank
     *
     * @required
     * @maps bank
     *
     * @param string[] $bank
     */
    public function setBank(array $bank): void
    {
        $this->bank = $bank;
    }

    /**
     * Returns Retries.
     * Number of retries for processing
     */
    public function getRetries(): int
    {
        return $this->retries;
    }

    /**
     * Sets Retries.
     * Number of retries for processing
     *
     * @required
     * @maps retries
     */
    public function setRetries(int $retries): void
    {
        $this->retries = $retries;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['bank']    = $this->bank;
        $json['retries'] = $this->retries;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
