<?php

declare(strict_types=1);

/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MundiAPILib\Models;

use stdClass;

class GetCheckoutDebitCardPaymentResponse implements \JsonSerializable
{
    /**
     * @var string
     */
    private $statementDescriptor;

    /**
     * @var GetPaymentAuthenticationResponse
     */
    private $authentication;

    /**
     * @param string $statementDescriptor
     * @param GetPaymentAuthenticationResponse $authentication
     */
    public function __construct(string $statementDescriptor, GetPaymentAuthenticationResponse $authentication)
    {
        $this->statementDescriptor = $statementDescriptor;
        $this->authentication = $authentication;
    }

    /**
     * Returns Statement Descriptor.
     * Descrição na fatura
     */
    public function getStatementDescriptor(): string
    {
        return $this->statementDescriptor;
    }

    /**
     * Sets Statement Descriptor.
     * Descrição na fatura
     *
     * @required
     * @maps statement_descriptor
     */
    public function setStatementDescriptor(string $statementDescriptor): void
    {
        $this->statementDescriptor = $statementDescriptor;
    }

    /**
     * Returns Authentication.
     * Payment Authentication response object data
     */
    public function getAuthentication(): GetPaymentAuthenticationResponse
    {
        return $this->authentication;
    }

    /**
     * Sets Authentication.
     * Payment Authentication response object data
     *
     * @required
     * @maps authentication
     */
    public function setAuthentication(GetPaymentAuthenticationResponse $authentication): void
    {
        $this->authentication = $authentication;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['statement_descriptor'] = $this->statementDescriptor;
        $json['authentication']       = $this->authentication;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
