<?php

declare(strict_types=1);

/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MundiAPILib\Models;

use MundiAPILib\Utils\DateTimeHelper;
use stdClass;

/**
 * Response object for getting a credit card
 */
class GetCardResponse implements \JsonSerializable
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var string
     */
    private $lastFourDigits;

    /**
     * @var string
     */
    private $brand;

    /**
     * @var string
     */
    private $holderName;

    /**
     * @var int
     */
    private $expMonth;

    /**
     * @var int
     */
    private $expYear;

    /**
     * @var string
     */
    private $status;

    /**
     * @var \DateTime
     */
    private $createdAt;

    /**
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @var GetBillingAddressResponse
     */
    private $billingAddress;

    /**
     * @var GetCustomerResponse|null
     */
    private $customer;

    /**
     * @var array<string,string>
     */
    private $metadata;

    /**
     * @var string
     */
    private $type;

    /**
     * @var string
     */
    private $holderDocument;

    /**
     * @var \DateTime|null
     */
    private $deletedAt;

    /**
     * @var string
     */
    private $firstSixDigits;

    /**
     * @var string
     */
    private $label;

    /**
     * @param string $id
     * @param string $lastFourDigits
     * @param string $brand
     * @param string $holderName
     * @param int $expMonth
     * @param int $expYear
     * @param string $status
     * @param \DateTime $createdAt
     * @param \DateTime $updatedAt
     * @param GetBillingAddressResponse $billingAddress
     * @param array<string,string> $metadata
     * @param string $type
     * @param string $holderDocument
     * @param string $firstSixDigits
     * @param string $label
     */
    public function __construct(
        string $id,
        string $lastFourDigits,
        string $brand,
        string $holderName,
        int $expMonth,
        int $expYear,
        string $status,
        \DateTime $createdAt,
        \DateTime $updatedAt,
        GetBillingAddressResponse $billingAddress,
        array $metadata,
        string $type,
        string $holderDocument,
        string $firstSixDigits,
        string $label
    ) {
        $this->id = $id;
        $this->lastFourDigits = $lastFourDigits;
        $this->brand = $brand;
        $this->holderName = $holderName;
        $this->expMonth = $expMonth;
        $this->expYear = $expYear;
        $this->status = $status;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->billingAddress = $billingAddress;
        $this->metadata = $metadata;
        $this->type = $type;
        $this->holderDocument = $holderDocument;
        $this->firstSixDigits = $firstSixDigits;
        $this->label = $label;
    }

    /**
     * Returns Id.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Last Four Digits.
     */
    public function getLastFourDigits(): string
    {
        return $this->lastFourDigits;
    }

    /**
     * Sets Last Four Digits.
     *
     * @required
     * @maps last_four_digits
     */
    public function setLastFourDigits(string $lastFourDigits): void
    {
        $this->lastFourDigits = $lastFourDigits;
    }

    /**
     * Returns Brand.
     */
    public function getBrand(): string
    {
        return $this->brand;
    }

    /**
     * Sets Brand.
     *
     * @required
     * @maps brand
     */
    public function setBrand(string $brand): void
    {
        $this->brand = $brand;
    }

    /**
     * Returns Holder Name.
     */
    public function getHolderName(): string
    {
        return $this->holderName;
    }

    /**
     * Sets Holder Name.
     *
     * @required
     * @maps holder_name
     */
    public function setHolderName(string $holderName): void
    {
        $this->holderName = $holderName;
    }

    /**
     * Returns Exp Month.
     */
    public function getExpMonth(): int
    {
        return $this->expMonth;
    }

    /**
     * Sets Exp Month.
     *
     * @required
     * @maps exp_month
     */
    public function setExpMonth(int $expMonth): void
    {
        $this->expMonth = $expMonth;
    }

    /**
     * Returns Exp Year.
     */
    public function getExpYear(): int
    {
        return $this->expYear;
    }

    /**
     * Sets Exp Year.
     *
     * @required
     * @maps exp_year
     */
    public function setExpYear(int $expYear): void
    {
        $this->expYear = $expYear;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @required
     * @maps status
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Created At.
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     *
     * @required
     * @maps created_at
     * @factory \MundiAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreatedAt(\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Updated At.
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->updatedAt;
    }

    /**
     * Sets Updated At.
     *
     * @required
     * @maps updated_at
     * @factory \MundiAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setUpdatedAt(\DateTime $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Returns Billing Address.
     */
    public function getBillingAddress(): GetBillingAddressResponse
    {
        return $this->billingAddress;
    }

    /**
     * Sets Billing Address.
     *
     * @required
     * @maps billing_address
     */
    public function setBillingAddress(GetBillingAddressResponse $billingAddress): void
    {
        $this->billingAddress = $billingAddress;
    }

    /**
     * Returns Customer.
     */
    public function getCustomer(): ?GetCustomerResponse
    {
        return $this->customer;
    }

    /**
     * Sets Customer.
     *
     * @maps customer
     */
    public function setCustomer(?GetCustomerResponse $customer): void
    {
        $this->customer = $customer;
    }

    /**
     * Returns Metadata.
     *
     * @return array<string,string>
     */
    public function getMetadata(): array
    {
        return $this->metadata;
    }

    /**
     * Sets Metadata.
     *
     * @required
     * @maps metadata
     *
     * @param array<string,string> $metadata
     */
    public function setMetadata(array $metadata): void
    {
        $this->metadata = $metadata;
    }

    /**
     * Returns Type.
     * Card type
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * Card type
     *
     * @required
     * @maps type
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Holder Document.
     * Document number for the card's holder
     */
    public function getHolderDocument(): string
    {
        return $this->holderDocument;
    }

    /**
     * Sets Holder Document.
     * Document number for the card's holder
     *
     * @required
     * @maps holder_document
     */
    public function setHolderDocument(string $holderDocument): void
    {
        $this->holderDocument = $holderDocument;
    }

    /**
     * Returns Deleted At.
     */
    public function getDeletedAt(): ?\DateTime
    {
        return $this->deletedAt;
    }

    /**
     * Sets Deleted At.
     *
     * @maps deleted_at
     * @factory \MundiAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDeletedAt(?\DateTime $deletedAt): void
    {
        $this->deletedAt = $deletedAt;
    }

    /**
     * Returns First Six Digits.
     * First six digits
     */
    public function getFirstSixDigits(): string
    {
        return $this->firstSixDigits;
    }

    /**
     * Sets First Six Digits.
     * First six digits
     *
     * @required
     * @maps first_six_digits
     */
    public function setFirstSixDigits(string $firstSixDigits): void
    {
        $this->firstSixDigits = $firstSixDigits;
    }

    /**
     * Returns Label.
     */
    public function getLabel(): string
    {
        return $this->label;
    }

    /**
     * Sets Label.
     *
     * @required
     * @maps label
     */
    public function setLabel(string $label): void
    {
        $this->label = $label;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']               = $this->id;
        $json['last_four_digits'] = $this->lastFourDigits;
        $json['brand']            = $this->brand;
        $json['holder_name']      = $this->holderName;
        $json['exp_month']        = $this->expMonth;
        $json['exp_year']         = $this->expYear;
        $json['status']           = $this->status;
        $json['created_at']       = DateTimeHelper::toRfc3339DateTime($this->createdAt);
        $json['updated_at']       = DateTimeHelper::toRfc3339DateTime($this->updatedAt);
        $json['billing_address']  = $this->billingAddress;
        if (isset($this->customer)) {
            $json['customer']     = $this->customer;
        }
        $json['metadata']         = $this->metadata;
        $json['type']             = $this->type;
        $json['holder_document']  = $this->holderDocument;
        if (isset($this->deletedAt)) {
            $json['deleted_at']   = DateTimeHelper::toRfc3339DateTime($this->deletedAt);
        }
        $json['first_six_digits'] = $this->firstSixDigits;
        $json['label']            = $this->label;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
