<?php

declare(strict_types=1);

/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MundiAPILib\Models;

use stdClass;

/**
 * Response object for getting an invoice item
 */
class GetInvoiceItemResponse implements \JsonSerializable
{
    /**
     * @var int
     */
    private $amount;

    /**
     * @var string
     */
    private $description;

    /**
     * @var GetPricingSchemeResponse
     */
    private $pricingScheme;

    /**
     * @var GetPriceBracketResponse
     */
    private $priceBracket;

    /**
     * @var int|null
     */
    private $quantity;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string
     */
    private $subscriptionItemId;

    /**
     * @param int $amount
     * @param string $description
     * @param GetPricingSchemeResponse $pricingScheme
     * @param GetPriceBracketResponse $priceBracket
     * @param string $subscriptionItemId
     */
    public function __construct(
        int $amount,
        string $description,
        GetPricingSchemeResponse $pricingScheme,
        GetPriceBracketResponse $priceBracket,
        string $subscriptionItemId
    ) {
        $this->amount = $amount;
        $this->description = $description;
        $this->pricingScheme = $pricingScheme;
        $this->priceBracket = $priceBracket;
        $this->subscriptionItemId = $subscriptionItemId;
    }

    /**
     * Returns Amount.
     */
    public function getAmount(): int
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     *
     * @required
     * @maps amount
     */
    public function setAmount(int $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Description.
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @required
     * @maps description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Pricing Scheme.
     */
    public function getPricingScheme(): GetPricingSchemeResponse
    {
        return $this->pricingScheme;
    }

    /**
     * Sets Pricing Scheme.
     *
     * @required
     * @maps pricing_scheme
     */
    public function setPricingScheme(GetPricingSchemeResponse $pricingScheme): void
    {
        $this->pricingScheme = $pricingScheme;
    }

    /**
     * Returns Price Bracket.
     */
    public function getPriceBracket(): GetPriceBracketResponse
    {
        return $this->priceBracket;
    }

    /**
     * Sets Price Bracket.
     *
     * @required
     * @maps price_bracket
     */
    public function setPriceBracket(GetPriceBracketResponse $priceBracket): void
    {
        $this->priceBracket = $priceBracket;
    }

    /**
     * Returns Quantity.
     */
    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    /**
     * Sets Quantity.
     *
     * @maps quantity
     */
    public function setQuantity(?int $quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * Returns Name.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Subscription Item Id.
     * Subscription Item Id
     */
    public function getSubscriptionItemId(): string
    {
        return $this->subscriptionItemId;
    }

    /**
     * Sets Subscription Item Id.
     * Subscription Item Id
     *
     * @required
     * @maps subscription_item_id
     */
    public function setSubscriptionItemId(string $subscriptionItemId): void
    {
        $this->subscriptionItemId = $subscriptionItemId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['amount']               = $this->amount;
        $json['description']          = $this->description;
        $json['pricing_scheme']       = $this->pricingScheme;
        $json['price_bracket']        = $this->priceBracket;
        if (isset($this->quantity)) {
            $json['quantity']         = $this->quantity;
        }
        if (isset($this->name)) {
            $json['name']             = $this->name;
        }
        $json['subscription_item_id'] = $this->subscriptionItemId;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
