<?php

declare(strict_types=1);

/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MundiAPILib\Models;

use stdClass;

/**
 * Response object for getting a pricing scheme
 */
class GetPricingSchemeResponse implements \JsonSerializable
{
    /**
     * @var int
     */
    private $price;

    /**
     * @var string
     */
    private $schemeType;

    /**
     * @var GetPriceBracketResponse[]
     */
    private $priceBrackets;

    /**
     * @var int|null
     */
    private $minimumPrice;

    /**
     * @var float|null
     */
    private $percentage;

    /**
     * @param int $price
     * @param string $schemeType
     * @param GetPriceBracketResponse[] $priceBrackets
     */
    public function __construct(int $price, string $schemeType, array $priceBrackets)
    {
        $this->price = $price;
        $this->schemeType = $schemeType;
        $this->priceBrackets = $priceBrackets;
    }

    /**
     * Returns Price.
     */
    public function getPrice(): int
    {
        return $this->price;
    }

    /**
     * Sets Price.
     *
     * @required
     * @maps price
     */
    public function setPrice(int $price): void
    {
        $this->price = $price;
    }

    /**
     * Returns Scheme Type.
     */
    public function getSchemeType(): string
    {
        return $this->schemeType;
    }

    /**
     * Sets Scheme Type.
     *
     * @required
     * @maps scheme_type
     */
    public function setSchemeType(string $schemeType): void
    {
        $this->schemeType = $schemeType;
    }

    /**
     * Returns Price Brackets.
     *
     * @return GetPriceBracketResponse[]
     */
    public function getPriceBrackets(): array
    {
        return $this->priceBrackets;
    }

    /**
     * Sets Price Brackets.
     *
     * @required
     * @maps price_brackets
     *
     * @param GetPriceBracketResponse[] $priceBrackets
     */
    public function setPriceBrackets(array $priceBrackets): void
    {
        $this->priceBrackets = $priceBrackets;
    }

    /**
     * Returns Minimum Price.
     */
    public function getMinimumPrice(): ?int
    {
        return $this->minimumPrice;
    }

    /**
     * Sets Minimum Price.
     *
     * @maps minimum_price
     */
    public function setMinimumPrice(?int $minimumPrice): void
    {
        $this->minimumPrice = $minimumPrice;
    }

    /**
     * Returns Percentage.
     * percentual value used in pricing_scheme Percent
     */
    public function getPercentage(): ?float
    {
        return $this->percentage;
    }

    /**
     * Sets Percentage.
     * percentual value used in pricing_scheme Percent
     *
     * @maps percentage
     */
    public function setPercentage(?float $percentage): void
    {
        $this->percentage = $percentage;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['price']             = $this->price;
        $json['scheme_type']       = $this->schemeType;
        $json['price_brackets']    = $this->priceBrackets;
        if (isset($this->minimumPrice)) {
            $json['minimum_price'] = $this->minimumPrice;
        }
        if (isset($this->percentage)) {
            $json['percentage']    = $this->percentage;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
