<?php

declare(strict_types=1);

/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MundiAPILib\Models;

use stdClass;

class GetPhonesResponse implements \JsonSerializable
{
    /**
     * @var GetPhoneResponse
     */
    private $homePhone;

    /**
     * @var GetPhoneResponse
     */
    private $mobilePhone;

    /**
     * @param GetPhoneResponse $homePhone
     * @param GetPhoneResponse $mobilePhone
     */
    public function __construct(GetPhoneResponse $homePhone, GetPhoneResponse $mobilePhone)
    {
        $this->homePhone = $homePhone;
        $this->mobilePhone = $mobilePhone;
    }

    /**
     * Returns Home Phone.
     */
    public function getHomePhone(): GetPhoneResponse
    {
        return $this->homePhone;
    }

    /**
     * Sets Home Phone.
     *
     * @required
     * @maps home_phone
     */
    public function setHomePhone(GetPhoneResponse $homePhone): void
    {
        $this->homePhone = $homePhone;
    }

    /**
     * Returns Mobile Phone.
     */
    public function getMobilePhone(): GetPhoneResponse
    {
        return $this->mobilePhone;
    }

    /**
     * Sets Mobile Phone.
     *
     * @required
     * @maps mobile_phone
     */
    public function setMobilePhone(GetPhoneResponse $mobilePhone): void
    {
        $this->mobilePhone = $mobilePhone;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['home_phone']   = $this->homePhone;
        $json['mobile_phone'] = $this->mobilePhone;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
