<?php

declare(strict_types=1);

/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MundiAPILib\Models;

use MundiAPILib\Utils\DateTimeHelper;
use stdClass;

/**
 * Response object for getting the shipping data
 */
class GetShippingResponse implements \JsonSerializable
{
    /**
     * @var int
     */
    private $amount;

    /**
     * @var string
     */
    private $description;

    /**
     * @var string
     */
    private $recipientName;

    /**
     * @var string
     */
    private $recipientPhone;

    /**
     * @var GetAddressResponse
     */
    private $address;

    /**
     * @var \DateTime|null
     */
    private $maxDeliveryDate;

    /**
     * @var \DateTime|null
     */
    private $estimatedDeliveryDate;

    /**
     * @var string
     */
    private $type;

    /**
     * @param int $amount
     * @param string $description
     * @param string $recipientName
     * @param string $recipientPhone
     * @param GetAddressResponse $address
     * @param string $type
     */
    public function __construct(
        int $amount,
        string $description,
        string $recipientName,
        string $recipientPhone,
        GetAddressResponse $address,
        string $type
    ) {
        $this->amount = $amount;
        $this->description = $description;
        $this->recipientName = $recipientName;
        $this->recipientPhone = $recipientPhone;
        $this->address = $address;
        $this->type = $type;
    }

    /**
     * Returns Amount.
     */
    public function getAmount(): int
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     *
     * @required
     * @maps amount
     */
    public function setAmount(int $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Description.
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @required
     * @maps description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Recipient Name.
     */
    public function getRecipientName(): string
    {
        return $this->recipientName;
    }

    /**
     * Sets Recipient Name.
     *
     * @required
     * @maps recipient_name
     */
    public function setRecipientName(string $recipientName): void
    {
        $this->recipientName = $recipientName;
    }

    /**
     * Returns Recipient Phone.
     */
    public function getRecipientPhone(): string
    {
        return $this->recipientPhone;
    }

    /**
     * Sets Recipient Phone.
     *
     * @required
     * @maps recipient_phone
     */
    public function setRecipientPhone(string $recipientPhone): void
    {
        $this->recipientPhone = $recipientPhone;
    }

    /**
     * Returns Address.
     */
    public function getAddress(): GetAddressResponse
    {
        return $this->address;
    }

    /**
     * Sets Address.
     *
     * @required
     * @maps address
     */
    public function setAddress(GetAddressResponse $address): void
    {
        $this->address = $address;
    }

    /**
     * Returns Max Delivery Date.
     * Data máxima de entrega
     */
    public function getMaxDeliveryDate(): ?\DateTime
    {
        return $this->maxDeliveryDate;
    }

    /**
     * Sets Max Delivery Date.
     * Data máxima de entrega
     *
     * @maps max_delivery_date
     * @factory \MundiAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setMaxDeliveryDate(?\DateTime $maxDeliveryDate): void
    {
        $this->maxDeliveryDate = $maxDeliveryDate;
    }

    /**
     * Returns Estimated Delivery Date.
     * Prazo estimado de entrega
     */
    public function getEstimatedDeliveryDate(): ?\DateTime
    {
        return $this->estimatedDeliveryDate;
    }

    /**
     * Sets Estimated Delivery Date.
     * Prazo estimado de entrega
     *
     * @maps estimated_delivery_date
     * @factory \MundiAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setEstimatedDeliveryDate(?\DateTime $estimatedDeliveryDate): void
    {
        $this->estimatedDeliveryDate = $estimatedDeliveryDate;
    }

    /**
     * Returns Type.
     * Shipping Type
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * Shipping Type
     *
     * @required
     * @maps type
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['amount']                      = $this->amount;
        $json['description']                 = $this->description;
        $json['recipient_name']              = $this->recipientName;
        $json['recipient_phone']             = $this->recipientPhone;
        $json['address']                     = $this->address;
        if (isset($this->maxDeliveryDate)) {
            $json['max_delivery_date']       = DateTimeHelper::toRfc3339DateTime($this->maxDeliveryDate);
        }
        if (isset($this->estimatedDeliveryDate)) {
            $json['estimated_delivery_date'] = DateTimeHelper::toRfc3339DateTime($this->estimatedDeliveryDate);
        }
        $json['type']                        = $this->type;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
