<?php

declare(strict_types=1);

/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MundiAPILib\Models;

use MundiAPILib\Utils\DateTimeHelper;
use stdClass;

class GetSubscriptionItemResponse implements \JsonSerializable
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var string
     */
    private $description;

    /**
     * @var string
     */
    private $status;

    /**
     * @var \DateTime
     */
    private $createdAt;

    /**
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @var GetPricingSchemeResponse
     */
    private $pricingScheme;

    /**
     * @var GetDiscountResponse[]
     */
    private $discounts;

    /**
     * @var GetIncrementResponse[]
     */
    private $increments;

    /**
     * @var GetSubscriptionResponse
     */
    private $subscription;

    /**
     * @var string
     */
    private $name;

    /**
     * @var int|null
     */
    private $quantity;

    /**
     * @var int|null
     */
    private $cycles;

    /**
     * @var \DateTime|null
     */
    private $deletedAt;

    /**
     * @param string $id
     * @param string $description
     * @param string $status
     * @param \DateTime $createdAt
     * @param \DateTime $updatedAt
     * @param GetPricingSchemeResponse $pricingScheme
     * @param GetDiscountResponse[] $discounts
     * @param GetIncrementResponse[] $increments
     * @param GetSubscriptionResponse $subscription
     * @param string $name
     */
    public function __construct(
        string $id,
        string $description,
        string $status,
        \DateTime $createdAt,
        \DateTime $updatedAt,
        GetPricingSchemeResponse $pricingScheme,
        array $discounts,
        array $increments,
        GetSubscriptionResponse $subscription,
        string $name
    ) {
        $this->id = $id;
        $this->description = $description;
        $this->status = $status;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->pricingScheme = $pricingScheme;
        $this->discounts = $discounts;
        $this->increments = $increments;
        $this->subscription = $subscription;
        $this->name = $name;
    }

    /**
     * Returns Id.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Description.
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @required
     * @maps description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @required
     * @maps status
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Created At.
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     *
     * @required
     * @maps created_at
     * @factory \MundiAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreatedAt(\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Updated At.
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->updatedAt;
    }

    /**
     * Sets Updated At.
     *
     * @required
     * @maps updated_at
     * @factory \MundiAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setUpdatedAt(\DateTime $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Returns Pricing Scheme.
     */
    public function getPricingScheme(): GetPricingSchemeResponse
    {
        return $this->pricingScheme;
    }

    /**
     * Sets Pricing Scheme.
     *
     * @required
     * @maps pricing_scheme
     */
    public function setPricingScheme(GetPricingSchemeResponse $pricingScheme): void
    {
        $this->pricingScheme = $pricingScheme;
    }

    /**
     * Returns Discounts.
     *
     * @return GetDiscountResponse[]
     */
    public function getDiscounts(): array
    {
        return $this->discounts;
    }

    /**
     * Sets Discounts.
     *
     * @required
     * @maps discounts
     *
     * @param GetDiscountResponse[] $discounts
     */
    public function setDiscounts(array $discounts): void
    {
        $this->discounts = $discounts;
    }

    /**
     * Returns Increments.
     *
     * @return GetIncrementResponse[]
     */
    public function getIncrements(): array
    {
        return $this->increments;
    }

    /**
     * Sets Increments.
     *
     * @required
     * @maps increments
     *
     * @param GetIncrementResponse[] $increments
     */
    public function setIncrements(array $increments): void
    {
        $this->increments = $increments;
    }

    /**
     * Returns Subscription.
     */
    public function getSubscription(): GetSubscriptionResponse
    {
        return $this->subscription;
    }

    /**
     * Sets Subscription.
     *
     * @required
     * @maps subscription
     */
    public function setSubscription(GetSubscriptionResponse $subscription): void
    {
        $this->subscription = $subscription;
    }

    /**
     * Returns Name.
     * Item name
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * Item name
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Quantity.
     */
    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    /**
     * Sets Quantity.
     *
     * @maps quantity
     */
    public function setQuantity(?int $quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * Returns Cycles.
     */
    public function getCycles(): ?int
    {
        return $this->cycles;
    }

    /**
     * Sets Cycles.
     *
     * @maps cycles
     */
    public function setCycles(?int $cycles): void
    {
        $this->cycles = $cycles;
    }

    /**
     * Returns Deleted At.
     */
    public function getDeletedAt(): ?\DateTime
    {
        return $this->deletedAt;
    }

    /**
     * Sets Deleted At.
     *
     * @maps deleted_at
     * @factory \MundiAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDeletedAt(?\DateTime $deletedAt): void
    {
        $this->deletedAt = $deletedAt;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']             = $this->id;
        $json['description']    = $this->description;
        $json['status']         = $this->status;
        $json['created_at']     = DateTimeHelper::toRfc3339DateTime($this->createdAt);
        $json['updated_at']     = DateTimeHelper::toRfc3339DateTime($this->updatedAt);
        $json['pricing_scheme'] = $this->pricingScheme;
        $json['discounts']      = $this->discounts;
        $json['increments']     = $this->increments;
        $json['subscription']   = $this->subscription;
        $json['name']           = $this->name;
        if (isset($this->quantity)) {
            $json['quantity']   = $this->quantity;
        }
        if (isset($this->cycles)) {
            $json['cycles']     = $this->cycles;
        }
        if (isset($this->deletedAt)) {
            $json['deleted_at'] = DateTimeHelper::toRfc3339DateTime($this->deletedAt);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
