<?php

declare(strict_types=1);

/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MundiAPILib\Models;

use MundiAPILib\Utils\DateTimeHelper;
use stdClass;

/**
 * Request for updating the start date from a subscription
 */
class UpdateSubscriptionStartAtRequest implements \JsonSerializable
{
    /**
     * @var \DateTime
     */
    private $startAt;

    /**
     * @param \DateTime $startAt
     */
    public function __construct(\DateTime $startAt)
    {
        $this->startAt = $startAt;
    }

    /**
     * Returns Start At.
     * The date when the subscription periods will start
     */
    public function getStartAt(): \DateTime
    {
        return $this->startAt;
    }

    /**
     * Sets Start At.
     * The date when the subscription periods will start
     *
     * @required
     * @maps start_at
     * @factory \MundiAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setStartAt(\DateTime $startAt): void
    {
        $this->startAt = $startAt;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['start_at'] = DateTimeHelper::toRfc3339DateTime($this->startAt);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
