<?php

declare(strict_types=1);

/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MundiAPILib\Models;

use stdClass;

/**
 * Request for updating a subscription's payment method
 */
class UpdateSubscriptionPaymentMethodRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $paymentMethod;

    /**
     * @var string
     */
    private $cardId;

    /**
     * @var CreateCardRequest
     */
    private $card;

    /**
     * @var string|null
     */
    private $cardToken;

    /**
     * @param string $paymentMethod
     * @param string $cardId
     * @param CreateCardRequest $card
     */
    public function __construct(string $paymentMethod, string $cardId, CreateCardRequest $card)
    {
        $this->paymentMethod = $paymentMethod;
        $this->cardId = $cardId;
        $this->card = $card;
    }

    /**
     * Returns Payment Method.
     * The new payment method
     */
    public function getPaymentMethod(): string
    {
        return $this->paymentMethod;
    }

    /**
     * Sets Payment Method.
     * The new payment method
     *
     * @required
     * @maps payment_method
     */
    public function setPaymentMethod(string $paymentMethod): void
    {
        $this->paymentMethod = $paymentMethod;
    }

    /**
     * Returns Card Id.
     * Card id
     */
    public function getCardId(): string
    {
        return $this->cardId;
    }

    /**
     * Sets Card Id.
     * Card id
     *
     * @required
     * @maps card_id
     */
    public function setCardId(string $cardId): void
    {
        $this->cardId = $cardId;
    }

    /**
     * Returns Card.
     * Card data
     */
    public function getCard(): CreateCardRequest
    {
        return $this->card;
    }

    /**
     * Sets Card.
     * Card data
     *
     * @required
     * @maps card
     */
    public function setCard(CreateCardRequest $card): void
    {
        $this->card = $card;
    }

    /**
     * Returns Card Token.
     * The Card Token
     */
    public function getCardToken(): ?string
    {
        return $this->cardToken;
    }

    /**
     * Sets Card Token.
     * The Card Token
     *
     * @maps card_token
     */
    public function setCardToken(?string $cardToken): void
    {
        $this->cardToken = $cardToken;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['payment_method'] = $this->paymentMethod;
        $json['card_id']        = $this->cardId;
        $json['card']           = $this->card;
        if (isset($this->cardToken)) {
            $json['card_token'] = $this->cardToken;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
