<?php

declare(strict_types=1);

/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MundiAPILib\Models;

use stdClass;

/**
 * Request for updating the card from a subscription
 */
class UpdateSubscriptionCardRequest implements \JsonSerializable
{
    /**
     * @var CreateCardRequest
     */
    private $card;

    /**
     * @var string
     */
    private $cardId;

    /**
     * @param CreateCardRequest $card
     * @param string $cardId
     */
    public function __construct(CreateCardRequest $card, string $cardId)
    {
        $this->card = $card;
        $this->cardId = $cardId;
    }

    /**
     * Returns Card.
     * Credit card data
     */
    public function getCard(): CreateCardRequest
    {
        return $this->card;
    }

    /**
     * Sets Card.
     * Credit card data
     *
     * @required
     * @maps card
     */
    public function setCard(CreateCardRequest $card): void
    {
        $this->card = $card;
    }

    /**
     * Returns Card Id.
     * Credit card id
     */
    public function getCardId(): string
    {
        return $this->cardId;
    }

    /**
     * Sets Card Id.
     * Credit card id
     *
     * @required
     * @maps card_id
     */
    public function setCardId(string $cardId): void
    {
        $this->cardId = $cardId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['card']    = $this->card;
        $json['card_id'] = $this->cardId;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
