<?php

declare(strict_types=1);

/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MundiAPILib\Models;

use stdClass;

class UpdateSubscriptionDueDaysRequest implements \JsonSerializable
{
    /**
     * @var int
     */
    private $boletoDueDays;

    /**
     * @param int $boletoDueDays
     */
    public function __construct(int $boletoDueDays)
    {
        $this->boletoDueDays = $boletoDueDays;
    }

    /**
     * Returns Boleto Due Days.
     */
    public function getBoletoDueDays(): int
    {
        return $this->boletoDueDays;
    }

    /**
     * Sets Boleto Due Days.
     *
     * @required
     * @maps boleto_due_days
     */
    public function setBoletoDueDays(int $boletoDueDays): void
    {
        $this->boletoDueDays = $boletoDueDays;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['boleto_due_days'] = $this->boletoDueDays;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
