/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.mundipagg.api;

import com.mundipagg.api.controllers.ChargesController;
import com.mundipagg.api.controllers.CustomersController;
import com.mundipagg.api.controllers.InvoicesController;
import com.mundipagg.api.controllers.OrdersController;
import com.mundipagg.api.controllers.PlansController;
import com.mundipagg.api.controllers.RecipientsController;
import com.mundipagg.api.controllers.SubscriptionsController;
import com.mundipagg.api.controllers.TokensController;
import com.mundipagg.api.controllers.TransactionsController;
import com.mundipagg.api.controllers.TransfersController;

/**
 * Gateway interface for the library.
 * This acts as a factory for Controllers.
 * It holds the state of the SDK.
 */
public interface MundiAPIClientInterface extends Configuration {
    
    /**
     * Provides access to Customers controller.
     * @return Returns the CustomersController instance
     */
    CustomersController getCustomersController();

    /**
     * Provides access to Charges controller.
     * @return Returns the ChargesController instance
     */
    ChargesController getChargesController();

    /**
     * Provides access to Recipients controller.
     * @return Returns the RecipientsController instance
     */
    RecipientsController getRecipientsController();

    /**
     * Provides access to Subscriptions controller.
     * @return Returns the SubscriptionsController instance
     */
    SubscriptionsController getSubscriptionsController();

    /**
     * Provides access to Invoices controller.
     * @return Returns the InvoicesController instance
     */
    InvoicesController getInvoicesController();

    /**
     * Provides access to Orders controller.
     * @return Returns the OrdersController instance
     */
    OrdersController getOrdersController();

    /**
     * Provides access to Tokens controller.
     * @return Returns the TokensController instance
     */
    TokensController getTokensController();

    /**
     * Provides access to Plans controller.
     * @return Returns the PlansController instance
     */
    PlansController getPlansController();

    /**
     * Provides access to Transactions controller.
     * @return Returns the TransactionsController instance
     */
    TransactionsController getTransactionsController();

    /**
     * Provides access to Transfers controller.
     * @return Returns the TransfersController instance
     */
    TransfersController getTransfersController();

}